### ISSUE TITLE
is there a preferred place to store images used on site?

### ISSUE THREAD

**Issue by davecampbell** [KYOSS/website#15]
where is the best place to store images that will be used on the website?
initially thinking of screengrabs to help with tutorial stuff but i guess this applies to any image that will be used on the site.
does it even matter?
i think i'd prefer a local asset folder for screengrabs, but that would certainly bloat the repo pretty fast.
any preferred external services, like imgur?

**Comment by jsquyres** [comment]
Per #13, I was having problems getting local non-Markdown assets to work properly (e.g., see https://github.com/KYOSS/website/pull/13#issuecomment-1155074910).  Hopefully, you won't run into the same problems.

I think that since this is a web site repo, it should be fine to include binary assets that are part of the web site.  Just don't make those assets too huge, because you're right: they become a permanent part of the git repo.

(disclaimer: I'm not a front-end kind of guy, so if there's different conventional wisdom about where to store binary assets, please feel free to contradict me!)

**Comment by InfoSec812** [comment]
For it to work properly with VuePress, all non-markdown assets should be put in `docs/.vuepress/public/` or a subdirectory therein. In the markdown, you then link to items in there from the root of the web site.

Example:

1. I add a file "docs/.vuepress/public/images/KYOSS_logo.png"
2. In my markdown, I link to it using `[KYOSS Logo](/images/KYOSS_logo.png)`
